name: CI
env:
  NEXT_PUBLIC_API_BASE_URL: ${{vars.NEXT_PUBLIC_API_BASE_URL}}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ...
      - uses: actions/checkout@v3
      - name: Setup Node 18 and Cache Dependencies ...
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run lint:code
      - run: npm run lint:styles
      - run: npm run prettier
      - run: npm run check:types

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code...
      - uses: actions/checkout@v3
      - run: ls -a .
      - name: Install Vercel CLI...
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information ...
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts ...
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: ls -a .
      - name: Upload Build Artifacts...
        uses: actions/upload-artifacts@v4
        with:
          name: build-artifacts
          path: |
          .next/
          .vercel/
  

  e2e:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - name: Download build Artifacts...
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v3
      - name: Download Build Artifacts...
        uses: actions/download-artifacts@v4

      - run: ls -a .
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
